const REGISTER_USER = 'REGISTER_USER';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';

const LOG_OUT = 'LOG_OUT';

const SET_CURRENT_USER = 'SET_CURRENT_USER';

const GET_PROFILE = 'GET_PROFILE';
const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

const GET_ALL_PROFILE = 'GET_ALL_PROFILE';
const GET_ALL_PROFILE_SUCCESS = 'GET_ALL_PROFILE_SUCCESS';
const GET_ALL_PROFILE_FAIL = 'GET_ALL_PROFILE_FAIL';

const RESET_PROFILE = 'RESET_PROFILE';
const REGISTER_PROFILE = 'REGISTER_PROFILE';
const REGISTER_PROFILE_SUCCESS = 'REGISTER_PROFILE_SUCCESS';
const REGISTER_PROFILE_FAIL = 'REGISTER_PROFILE_FAIL';

const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS';
const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL';

const ADD_EDUCATION = 'ADD_EDUCATION';
const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS';
const ADD_EDUCATION_FAIL = 'ADD_EXPERIENCE_FAIL';

const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL';

const DELETE_EDUCATION = 'DELETE_EDUCATION';
const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS';
const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL';

const ADD_POST = 'ADD_POST';
const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
const ADD_POST_FAIL = 'ADD_POST_FAIL';

const GET_ALL_POST = 'GET_ALL_POST';
const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS';
const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL';

const GET_POST = 'GET_POST';
const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
const GET_POST_FAIL = 'GET_POST_FAIL';

const DELETE_POST = 'DELETE_POST';
const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

const LIKE_POST = 'LIKE_POST';
const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
const LIKE_POST_FAIL = 'LIKE_POST_FAIL';

const ADD_COMMENT = 'ADD_COMMENT';
const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export {
  // Register user
  REGISTER_USER,
  REGISTER_USER_FAIL,
  REGISTER_USER_SUCCESS,
  // User login
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  // Set current user
  SET_CURRENT_USER,
  // Logout
  LOG_OUT,
  // Profile
  GET_PROFILE,
  GET_PROFILE_SUCCESS,
  GET_PROFILE_FAIL,
  // All profile
  GET_ALL_PROFILE,
  GET_ALL_PROFILE_SUCCESS,
  GET_ALL_PROFILE_FAIL,
  // Register profile
  RESET_PROFILE,
  REGISTER_PROFILE,
  REGISTER_PROFILE_SUCCESS,
  REGISTER_PROFILE_FAIL,
  // Add Experience
  ADD_EXPERIENCE,
  ADD_EXPERIENCE_SUCCESS,
  ADD_EXPERIENCE_FAIL,
  // Add Education
  ADD_EDUCATION,
  ADD_EDUCATION_SUCCESS,
  ADD_EDUCATION_FAIL,
  // Delete Experience
  DELETE_EXPERIENCE,
  DELETE_EXPERIENCE_SUCCESS,
  DELETE_EXPERIENCE_FAIL,
  // Delete Education
  DELETE_EDUCATION,
  DELETE_EDUCATION_SUCCESS,
  DELETE_EDUCATION_FAIL,
  // Add post
  ADD_POST,
  ADD_POST_SUCCESS,
  ADD_POST_FAIL,
  // Get All Posts
  GET_ALL_POST,
  GET_ALL_POST_SUCCESS,
  GET_ALL_POST_FAIL,
  // Remove Post
  DELETE_POST,
  DELETE_POST_SUCCESS,
  DELETE_POST_FAIL,
  // Like Post
  LIKE_POST,
  LIKE_POST_SUCCESS,
  LIKE_POST_FAIL,
  // Get Post
  GET_POST,
  GET_POST_SUCCESS,
  GET_POST_FAIL,
  // Add Comment
  ADD_COMMENT,
  ADD_COMMENT_SUCCESS,
  ADD_COMMENT_FAIL
};
